name: operation_kalkan
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  intl: ^0.20.2
  riverpod_annotation: ^3.0.3

dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.1
  riverpod_lint: ^3.0.1
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
